# Ch. 1 

* gradient boosting for shallow learning problems 
* deep learning for perceptual problems 

on page 22 

In [1]:
import numpy as np 

In [28]:
x = np.random.uniform(-5,5, (4,4))
y = np.random.uniform(-5,5, (4,4))

In [22]:
def naive_relu(x):
    assert len(x.shape) == 2
    
    x = x.copy()
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
            
    return x

In [30]:
naive_relu(x)

array([[2.84252693, 0.        , 1.96052552, 0.91985948],
       [0.        , 3.37685683, 0.        , 2.11250857],
       [3.13430744, 0.        , 0.        , 0.        ],
       [0.        , 4.78287969, 0.        , 0.        ]])

In [31]:
def naive_add(x, y):
    
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
            
    return x

In [32]:
naive_add(x,y)

array([[ 2.63696977, -2.30371666,  4.12741541, -3.06515319],
       [-0.13951455,  1.32102723, -5.60457475,  4.73492214],
       [ 1.79633823, -6.29120227, -2.33763904, -8.44410818],
       [-2.1028077 ,  8.60946413, -6.65281469, -7.59659039]])

In [33]:
z = x + y # element wise addition in numpy 
z = np.maximum(x, 0) # numpy implemented relu

In [47]:
q = z.copy()
q.shape

(4, 4)

In [50]:
q.reshape((16,1)).shape

(16, 1)

In [57]:
A = np.array([[1,5], [7,1]])
A.transpose()

array([[1, 7],
       [5, 1]])

On p. 46, ch. 2.4